set(tester_SETUP_PY_SETUP_MODULE "distutils.core")
set(tester_SETUP_PY_VERSION "0.0.0")
set(tester_SETUP_PY_SCRIPTS "")
set(tester_SETUP_PY_PACKAGES "tester")
set(tester_SETUP_PY_PACKAGE_DIRS "src/tester")
set(tester_SETUP_PY_MODULES "")
set(tester_SETUP_PY_MODULE_DIRS "")